### PR TITLE
RF_02.007.02-03 Add method to reset Jenkins theme to pass color tests

### PR DESCRIPTION
**Pull request by DenisProkofyev**

### CODE REVIEW

**Comment by DenisProkofyev** [comment]
[RF_02.007.02-03 | Delete Ignore annotations](https://trello.com/c/wdbu9h7S/440-rf0200702-03-delete-ignore-annotations)

**Review by KuperWoman — APPROVED** [review]
LGTM

**Review by aqaestuser — APPROVED** [review]
LGTM

**Comment by DenisProkofyev** [comment]
@KuperWoman, @aqaestuser, спасибо!

**Pull request merged**
