### PR TITLE
TC_00.004.26 + TC_00.004.27 + TC_00.004.28

### PR DESCRIPTION
**Pull request by anastasiia148**
add 3 new tests:  New item > Create Folder>Verify Folder is displayed on Dashboard
New item > Create Folder>Verify New Folder is Empty
New item > Create Folder>Verify Item Can Be moved to NewFolder

### CODE REVIEW

**Comment by anastasiia148** [comment]
[TC_00.004.28 | New item > Create Folder>VerifyNewItemCanBeMovedToFolder](https://trello.com/c/EUZ7xG7O/727-tc0000428-new-item-create-folderverifynewitemcanbemovedtofolder)

**Comment by anastasiia148** [comment]
[TC_00.004.27 | New item > Create Folder>VerifyCreatedFolderIsEmpty](https://trello.com/c/rKbxbS0i/726-tc0000427-new-item-create-folderverifycreatedfolderisempty)

**Comment by anastasiia148** [comment]
[TC_00.004.26 | New item > Create Folder>VerifyFolderIsDisplayedOnDashboard](https://trello.com/c/pcly1N6z/725-tc0000426-new-item-create-folderverifyfolderisdisplayedondashboard)

**Review by ArtemRazDva — APPROVED** [review]

**Review by verafes — APPROVED** [review]

**Comment by anastasiia148** [comment]
https://trello.com/c/rKbxbS0i
https://trello.com/c/pcly1N6z
https://trello.com/c/EUZ7xG7O

**Pull request merged**
