### PR TITLE
TC_03.001.04 | Multi-configuration project > Add description on Configuration page

### PR DESCRIPTION
**Pull request by KuperWoman**

### CODE REVIEW

**Comment by KuperWoman** [comment]
[TC_03.001.04 | Multi-configuration project > Add description on Configuration page](https://trello.com/c/gEkfHIxL/120-tc0300104-multi-configuration-project-add-description-on-configuration-page)

**Comment by KuperWoman** [comment]
[TC_03.001.04 | Multi-configuration project > Add description on Configuration page](https://trello.com/c/gEkfHIxL/120-tc0300104-multi-configuration-project-add-description-on-configuration-page)

**Comment by KuperWoman** [comment]
[TC_03.001.04 | Multi-configuration project > Add description on Configuration page](https://trello.com/c/gEkfHIxL/120-tc0300104-multi-configuration-project-add-description-on-configuration-page)

**Review by aqaestuser — APPROVED** [review]
LGTM

**Review by Tatsiana82 — APPROVED** [review]
LGTM

**Pull request merged**
