### PR TITLE
TC_01.010.02|Freestyle Project > Build > Remote Triggering

### PR DESCRIPTION
**Pull request by Volhabo**
https://trello.com/c/wgw6nkOX/561-tc0000423-item-sub-item-create-subfolder

### CODE REVIEW

**Review by AlyonkaNY — APPROVED** [review]
LGTM

**Review by AlyonkaNY — APPROVED** [review]
LGTM

**Comment by kgold2018** [comment]
LGTM

**Review by kgold2018 — APPROVED** [review]
LGTM

**Comment by sweetscripts** [comment]
I ignored your test. It failed in CI. Please check.  Thank you! @Volhabo 
`Tests run: 351, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 733.79 sec <<< FAILURE!
testFreestyleJobRemoteTriggering(school.redrover.JobRemoteTriggeringOBTest)  Time elapsed: 62.269 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //a[@tooltip='Success > Console Output'] (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1018-azure', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.60, chrome: {chromedriverVersion: 124.0.6367.60 (8771130bd84f..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:43985}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:43985/devtoo..., se:cdpVersion: 124.0.6367.60, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 83452a233626b3dbc62512fec5d50ce9
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.JobRemoteTriggeringOBTest.testFreestyleJobRemoteTriggering(JobRemoteTriggeringOBTest.java:119)`

**Pull request merged**
