### PR TITLE
TC_00.000.09

### PR DESCRIPTION
**Pull request by YuryHerasimau**
[TC_00.000.09 | New item > Create New item](https://trello.com/c/S3iRfWyE/104-tc0000009-new-item-create-new-item)

### CODE REVIEW

**Comment by YuryHerasimau** [comment]
[TC_00.000.09 | New item > Create New item](https://trello.com/c/S3iRfWyE/104-tc0000009-new-item-create-new-item)

**Review by MalkoSV — APPROVED** [review]
LGTM

**Review by AlyonkaNY — APPROVED** [review]
LGTM

**Review by kiramitt — APPROVED** [review]
LGTM

**Pull request merged**
