### PR TITLE
TC_04.004.08, TC _04.004.09 new changes

### PR DESCRIPTION
**Pull request by YuliyaD1985**
https://trello.com/c/wYMjt04L/552-tc0400408-folder-add-and-edit-descriptionedit-description
https://trello.com/c/SFM6q4Gf/553-tc0400409-folder-add-and-edit-description-delete-description

### CODE REVIEW

**Comment by YuliyaD1985** [comment]
[TC_04.004.09 | Folder > Add and edit description> Delete description](https://trello.com/c/SFM6q4Gf/553-tc0400409-folder-add-and-edit-description-delete-description)

**Comment by YuliyaD1985** [comment]
[TC_04.004.08 |Folder> Add and edit description>Edit description](https://trello.com/c/wYMjt04L/552-tc0400408-folder-add-and-edit-descriptionedit-description)

**Comment by YuliyaD1985** [comment]
[TC_04.004.08 |Folder> Add and edit description>Edit description](https://trello.com/c/wYMjt04L/552-tc0400408-folder-add-and-edit-descriptionedit-description)

**Review by sweetscripts — APPROVED** [review]
Looks good

**Review by MargaritaArcady — APPROVED** [review]

**Pull request merged**
