### PR TITLE
Yd/folder test

### PR DESCRIPTION
**Pull request by YuliyaD1985**
https://trello.com/c/DrXBROZm/185-tc00400103-folderrename-folder

### CODE REVIEW

**Comment by YuliyaD1985** [comment]
[TC_004.001.03 | Folder>Rename Folder](https://trello.com/c/DrXBROZm/185-tc00400103-folderrename-folder)

**Comment by sweetscripts** [comment]
Don't worry, it's good that conflicts happen in the learning stage.

**Review by LenaOrfanidi — APPROVED** [review]
Looks good to me

**Review by sweetscripts — APPROVED** [review]
Looks good

**Pull request merged**
