### PR TITLE
RF_03.001.01 | Multi-configuration project > Add description on the status page > POM

### PR DESCRIPTION
**Pull request by KuperWoman**

### CODE REVIEW

**Review by aqaestuser — APPROVED** [review]
LGTM

**Review by Tatsiana82 — APPROVED** [review]
LGTM

**Comment by KuperWoman** [comment]
[RF_03.001.01 | Multi-configuration project > Add description on the status page > POM](https://trello.com/c/MVgFg1V1/706-rf0300101-multi-configuration-project-add-description-on-the-status-page-pom)

**Review by Tatsiana82 — APPROVED** [review]
LGTM

**Pull request merged**
