### PR TITLE
Create a class for the Underdogs group, add the first test

### PR DESCRIPTION
**Pull request by tereshenkov29**

### CODE REVIEW

**Review by zapletin-dk — APPROVED** [review]
I'd rather chage By.xpath to By.id in 20 row 
String result = driver.findElement(By.id("name")).getText()

**Comment by tereshenkov29** [comment]
> I'd rather chage By.xpath to By.id in 20 row String result = driver.findElement(By.id("name")).getText()

maybe next time

**Comment by tereshenkov29** [comment]
> I'd rather chage By.xpath to By.id in 20 row String result = driver.findElement(By.id("name")).getText()

Actually, performed a new commit

**Review by aqaestuser — APPROVED** [review]
ok

**Pull request merged**
